# Numpy

- NumPy is an acronym for "Numeric Python" or "Numerical Python". 
- It is an open source extension module for Python. 
- Provides fast precompiled functions for mathematical and numerical routines. 
- NumPy and SciPy were created to do numerical and scientific computing in the most natural way with Python, not to be MATLAB® clones.

Important subtle difference from MATLAB : numpy arrays are *not* part of the core language. So they can be developed, extend, and modified without installing a new python.

<img src="numpy.png" style="background:none; border:none; box-shadow:none; display:inline; margin:0; vertical-align:middle;" width="100%">

# Advantages of using Numpy

- Array-oriented computing
- Efficiently implemented multi-dimensional arrays
- Designed for scientific computation

But before we dive into Numpy, let's take a detour through Python data types...


## Python Data Types

Python has five standard data types. 

- Number
- String
- List 
- Tuple
- Dictionary

In [29]:
# Numbers can be integers (including long), float, complex or boolean
a = 5
print('Integer:', a, type(a))

b = 51924361948403939480293840938
print('Long integer:', b, type(b))

c = 10.7
print('Float', c, type(c))

t, f = True, False
print('Boolean: ',t, type(t))

d = 9.322e-36j
print('Complex:', d, type(d))

Integer: 5 <class 'int'>
Long integer: 51924361948403939480293840938 <class 'int'>
Float 10.7 <class 'float'>
Boolean:  True <class 'bool'>
Complex: 9.322e-36j <class 'complex'>


In [1]:
# Strings are straight-forward as we saw with 'Hellow World!'

string = 'A mouse once bit my sister.'
print(string)

A mouse once bit my sister.


In [3]:
# Lists are the ones most similar to arrays, but not quite.
# List items can be from different types.
ll = [1.2, 23.6, 'foo', 11] ### <---- lists use square brackets!
print(ll)

# Lists are easy to append! Use in cases where you do not know the size of the input array!
ll.append('temp')
print(ll)

[1.2, 23.6, 'foo', 11]
[1.2, 23.6, 'foo', 11, 'temp']


In [5]:
# Tuples: similar to lists, but have an interesting quality: once created they cannot be changed.
# i.e., they are "immutable", they cannot be sorted, appended, etc.
# This is good for certain cases (e.g. they can be keys to a dictionary), 
# tuple items can not be from different types.

tup = (1,2,3,6.7) ### <---- use parenthesis for tuples
print(tup, type(tup))

oneItemTuple = (1,) ### <---- one item tuple should have trailing comma inside parenthesis
print(oneItemTuple, type(oneItemTuple))

number = (1)
print(number, type(number))

((1, 2, 3, 6.7), <type 'tuple'>)
((1,), <type 'tuple'>)
(1, <type 'int'>)


In [6]:
# Dictionary: We use curely braces for dictionaries.
dd = {'name': 'saeed'}
dd['lock'] = 1
dd['key'] = 2
print(dd)

{'lock': 1, 'name': 'saeed', 'key': 2}


## Numpy Data Types

Numpy arrays are a different data type, beyond the five above: the `ndarray`. Numpy arrays can only contain one type of data but there are lots of options as to what that type is. A full list of Numpy data types can be found here:

http://docs.scipy.org/doc/numpy/user/basics.types.html

- Always use the smallest data type that is appropriate for your data.
- Do not append to numpy arrays: it is hugely inefficient!  This is what `list`s are good for.


In [8]:
import numpy as np # importing numpy in namespace

# values evenly spaced within an interval, specify the STEP:
# np.arange(start, stop, step)
np.arange(0,10,1, dtype=np.float) # if you don't specify the data type, Python will use the one that takes the least space

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [68]:
# values evenly spaced within an interval, specify the NUMBER OF VALUES:
# np.linspace(star, stop, num=10)
np.linspace(0,9,10, dtype=np.int)

# there is also np.logspace
#np.logspace(0,1,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# create array from existing data:

a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [10]:
# another way to get a pre-filled array is to set all values to ones, zeros, or leave them empty:
a = np.ones(10)
print('Ones:', a)

b = np.zeros([2, 2])
print('Zeros:', b)



('Ones:', array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]))
('Zeros:', array([[ 0.,  0.],
       [ 0.,  0.]]))


# Attributes

Each Numpy array has some attributes:
`shape` (a tuple of the size in each dimension), `dtype` (data type of
entries), `size` (total # of entries), `ndim` (# of dimensions), `T` (transpose)


In [18]:
b = np.arange(2*2)
print('b.shape', b.shape)
a = b.reshape(2, 2)
print(a)
print('a.shape', a.shape)
print('a.dtype', a.dtype)
print('a.size' , a.size)
print('a.ndim', a.ndim)
print('a.T', a.T)

('b.shape', (4,))
[[0 1]
 [2 3]]
('a.shape', (2, 2))
('a.dtype', dtype('int64'))
('a.size', 4)
('a.ndim', 2)
('a.T', array([[0, 2],
       [1, 3]]))


# Array Broadcasting
![1.png](1.png)

# NumPy for Matlab users.

- Python uses 0 (zero) based indexing. The initial element of a sequence is found using a[0].
- In NumPy arrays have pass-by-reference semantics. Slice operations are views into an array. But in Matlab Slice operations copy parts of the array.
- In NumPy, we use bracket for array item indexing, but in Matlab we use pranthesis.


| Matlab          | NumPy         | Notes |
| :---------------|:--------------|:-----|
| ndims(a)        | a.ndim        | get the number of dimensions of an array |
| numel(a)        | a.size        | get the number of elements of an array |
| size(a)         | a.shape       | get the “size” of the matrix |
| size(a,n)       | a.shape[n-1]  | get the number of elements of the n-th dimension of array a. |
| [1 2; 4 5]      | array([[1.,2.], [4.,5.]]) | 2 x 2 matrix literal |
| [a b; c d]      | vstack([hstack([a,b]), hstack([c,d])]) | construct a matrix from blocks a, b, c, and d |
| a(end)	      | a[-1]	        | access last element in the 1xn matrix a |
| a(2,5)	      | a[1,4]	    | access element in second row, fifth column |
| a(2,:)	      | a[1] or a[1,:]| 	entire second row of a |
| a * b	          | a.dot(b)	    | matrix multiply |
| a .\* b	      | a * b	        | element-wise multiply |
| a./b	          | a/b	        | element-wise divide |
| a.^3			  | a\*\*3	    | element-wise exponentiation |
| rand(3,4)	      | np.random.rand(3,4) |	random 3x4 matrix |
| y=x(:)	      | y = x.flatten()|turn array into vector |



## Other Resources

- Numpy documentation:

http://docs.scipy.org/doc/numpy/

- Numpy documentation quickstart:

http://docs.scipy.org/doc/numpy/user/quickstart.html

- Numpy documentation basics:

http://docs.scipy.org/doc/numpy/user/basics.html

- Good Tutorial:

http://www.python-course.eu/numpy.php

- Another tutorial, which has a similar approach to ours:

http://cs231n.github.io/python-numpy-tutorial/

To actually show this as a presentation, the easiest thing is to do ``jupyter nbconvert --to slides <this file's name>.ipynb --post serve``